version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    volumes_from:
      - bundle
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
  bundle:
    image: busybox
    volumes:
      - /usr/src/app/vendor/bundle

